spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}