spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/bank?authSource=admin
application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000